Analysis descriptions
tonac/dsdsna4slack pull request #17
Opened 2018-01-01 20:41 UTC by marinzg

Please check the description in frontend/src/app/main/home/home.component.html since that is what's going into the documentation.

2018-01-05 02:13 UTC, laky55555 commented
Looks good, just few little things:
1. **Descriptions** are not in the same level
![image](https://user-images.githubusercontent.com/20819310/34592581-7d40f542-f1c5-11e7-905c-2ca4657d48b8.png)
1. In **Path length**, better description would be _The average distance between any two persons in a graph._
1. **Density description** is not completely correct for subscription graph. In subscription graph density is 1 if every person is subscripted to all analyzing channels
![image](https://user-images.githubusercontent.com/20819310/34592695-3daa2e66-f1c6-11e7-88f0-88867c4ba90a.png)

2018-01-05 02:14 UTC, laky55555 requested changes
Looks very nice. Can you just take a look over few changes I put

2018-01-07 12:44 UTC, marinzg commented on frontend/src/app/main/home/home.component.css
> +.feature {
Some comment.

2018-01-07 19:07 UTC, laky55555 approved these changes
Looked at it again, looks good :+1:

2018-01-07 20:49 UTC, merged